/* Generated by tex3ds */
#pragma once

#define Common_Bell_idx 0
#define Common_checkbox_idx 1
#define Common_checkbox_c_idx 2
#define Common_edit_idx 3
#define Common_Editor_idx 4
#define Common_hand_grab_idx 5
#define Common_hand_pan_idx 6
#define Common_hand_point_idx 7
#define Common_hand_select_idx 8
#define Common_icon_idx 9
#define Common_ItemHole_idx 10
#define Common_Letter_idx 11
#define Common_Manager_idx 12
