/* Generated by tex3ds */
#pragma once

#define Editor_About_idx 0
#define Editor_Acres_idx 1
#define Editor_Button_idx 2
#define Editor_Island_idx 3
#define Editor_Main_Street_idx 4
#define Editor_Profile_idx 5
#define Editor_Pwp_idx 6
#define Editor_Town_idx 7
#define Editor_Villagers_idx 8
