/* Generated by tex3ds */
#pragma once

#define GameSelect_Europe_idx 0
#define GameSelect_GameCart_idx 1
#define GameSelect_Icon_idx 2
#define GameSelect_IconWA_idx 3
#define GameSelect_Japan_idx 4
#define GameSelect_Korea_idx 5
#define GameSelect_SDCard_idx 6
#define GameSelect_USA_idx 7
