/* Generated by tex3ds */
#pragma once

#define Players_About_idx 0
#define Players_Appearance_idx 1
#define Players_House_idx 2
#define Players_Inventory_idx 3
#define Players_Mailbox_idx 4
#define Players_Mailbox_Unread_idx 5
#define Players_NoTPC_idx 6
#define Players_Patterns_idx 7
